service: buckets-permissions

package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json
  individually: true

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: sa-east-1
  timeout: 300

functions:
  app:
    handler: src/app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'